
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SWRProvider from "./SWRProvider";
import Header from "@/components/Layout/Header";
import { DarKModeProvider } from "@/contexts/DarkModeContext";
import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <DarKModeProvider>
          <SWRProvider>
            <Header />
            {children}
          </SWRProvider>
      </DarKModeProvider>
    </html>
  );
}
